name: "NikSativa CI"

on:
  push:
    branches:
      - "main"
      - $default-branch
    paths:
      - ".github/workflows/**"
      - "Package.swift"
      - "Source/**"
      - "Tests/**"
  pull_request:
    paths:
      - ".github/workflows/**"
      - "Package.swift"
      - "Source/**"
      - "Tests/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true
jobs:
  macOS:
    name: "macOS ${{ matrix.swift }}"
    runs-on: macos-latest
    env:
      OUTPUT_FILTER: ${{ matrix.outputFilter }}
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        swift:
          - "6.1"
          - "6.0"
          - "5.10"
          - "5.9"
        outputFilter:
          - xcbeautify --renderer github-actions
    steps:
      - uses: swift-actions/setup-swift@v2
        with:
          swift-version: ${{ matrix.swift }}
      - uses: actions/checkout@v4
      - name: Cache Swift packages
        uses: actions/cache@v3
        with:
          path: .build
          key: ${{ runner.os }}-swift-${{ matrix.swift }}-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-swift-${{ matrix.swift }}-
      - name: "Build ${{ matrix.swift }}"
        run: swift build -v | $OUTPUT_FILTER
      - name: "Test ${{ matrix.swift }}"
        run: swift test -v | $OUTPUT_FILTER
